---
# ***** U.S. SECURITY CLASSIFICATION: UNCLASSIFIED ***************************
# ***** U.S. EXPORT CONTROL CLASSIFICATION NUMBER (ECCN): EAR99 **************
#
# Common Software Factory Pipeline Template
#
# Copyright 2019-2023 - Lockheed Martin Corporation.
#
# For U.S. Government Users: The Government is granted Unlimited Rights in
# this pipeline template as defined in DFARS 252.227-7013 (a)(16) and
# 252.227-7014 (a)(16). The Government has the right to use, modify,
# reproduce, perform, display, release or disclose this computer software
# in whole or in part, in any manner, and for any purpose whatsoever,
# and to have or authorize others to do so.
#
# For All Other Users: This pipeline template contains Lockheed Martin
# Proprietary Information. If delivered under a contract, use of this pipeline
# template is subject to the terms of use as required by the contract under
# which it was delivered.  No other use is permitted without the prior written
# authorization of Lockheed Martin Corporation.
#
# For All Users: The classification, ECCN, and license terms in this file
# apply solely to this file. Software built or assembled by this pipeline
# template may be subject other licensing terms or other restrictions on use
# (e.g. export control). The recipient/user should check the markings on each
# item/software provided to ensure use consistent with its restrictions.
# ****************************** UNCLASSIFIED ********************************
#
# CI Jobs for sigstore-helm-charts repo
#
# version: {{version}}


#############################################################################################################
# This workflow definition is intended to prevent duplicate branch and MR pipelines running - one is plenty
#############################################################################################################
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: "$CI_COMMIT_BRANCH"

#############################################################################################################
# Remote and local included pipeline templates
#############################################################################################################
include:
  - remote: "https://pipeline-catalog.global.lmco.com/api/v1/modules/stages/v1.0.10/templates/stages.gitlab-ci.yml"
  - remote: "https://pipeline-catalog.global.lmco.com/api/v1/ez-registry/modules/node/v2.0.27/modules/node-cmd.yml"
  - remote: "https://pipeline-catalog.global.lmco.com/api/v1/global/modules/kaniko/v3.0.23/modules/kaniko-build.gitlab-ci.yml"

#############################################################################################################
# Variables
#############################################################################################################
variables:
  http_proxy: http://proxy-zsgov.external.lmco.com:80
  https_proxy: http://proxy-zsgov.external.lmco.com:80
  no_proxy: ".lmco.com,.LMCO.COM,*.lmco.com,*.LMCO.COM,127.0.0.1,localhost,.amazonaws.com,*.amazonaws.com"
  #############################################################################################################
  # Kaniko Variables
  #############################################################################################################
  DOCKER_BUILD_DIR: "."
  DOCKER_FILE: "docker/Dockerfile.alpine"
  DOCKER_REGISTRY: registry.gitlab.global.lmco.com:443
  ENABLE_KANIKO: "true"
  KANIKO_BOM_GEN: "false"
  #############################################################################################################
  # Node Variables
  #############################################################################################################
  ENABLE_NODE_CI: "true"
  ENABLE_NODE_BUILD: "true"
  ENABLE_NODE_LINT: "false"
  ENABLE_NODE_TEST: "false"
  ENABLE_NODE_PUBLISH: "false"
  # variable for tracking pipeline usage
  SWF_PIPELINE_METRICS_PIPELINES_NODE_BASIC: "false"

#############################################################################################################
   # Node Build
#############################################################################################################
node-build:
  artifacts:
    paths:
      - dist/

#############################################################################################################
# Parse Build version
#############################################################################################################
get_version:
  image: harbor.global.lmco.com/lmc.eo.swf.lmified/ext.hub.docker.com/redhat/ubi9:9.2
  stage: build
  script:
    - rm -rf /etc/yum.repos.d/*.repo
    - |
      cat << EOF >> /etc/yum.repos.d/efoss-ubi-appstream.repo
      [efoss-ubi9-appstream]
      name=Lockheed Martin Enterprise FOSS Proxy UBI 9 appstream
      baseurl=https://$EFOSS_USER:$EFOSS_TOKEN@nexus.global.lmco.com/repository/yum-ubi-9-proxy/x86_64/appstream/os/
      proxy=_none_
      failovermethod=priority
      enabled=1
      priority=1
      gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
      EOF
    - yum install jq -y
    - echo POM_VERSION=$(jq -r '.version' package.json) > variables.env
    - cat variables.env
  artifacts:
    reports:
      dotenv: variables.env

#############################################################################################################
# Kaniko Section
#############################################################################################################
kaniko:
  before_script:
    - |
      if [[ $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH ]]; then
        export DOCKER_TAG="$CI_COMMIT_REF_SLUG-$POM_VERSION"
      else
        export DOCKER_TAG="$CI_COMMIT_REF_SLUG-$POM_VERSION-$CI_COMMIT_SHORT_SHA"
      fi
    - echo DOCKER_TAG - $DOCKER_TAG
  rules:
    - if: $ENABLE_KANIKO == "true"
