// API Permissions
export const BOM_UPLOAD = 'BOM_UPLOAD';
export const VIEW_PORTFOLIO = 'VIEW_PORTFOLIO';
export const PORTFOLIO_MANAGEMENT = 'PORTFOLIO_MANAGEMENT';
export const PORTFOLIO_MANAGEMENT_CREATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const PORTFOLIO_MANAGEMENT_READ = 'PORTFOLIO_MANAGEMENT_CREATE';
export const PORTFOLIO_MANAGEMENT_UPDATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const PORTFOLIO_MANAGEMENT_DELETE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const VIEW_VULNERABILITY = 'PORTFOLIO_MANAGEMENT_CREATE';
export const VULNERABILITY_ANALYSIS = 'PORTFOLIO_MANAGEMENT_CREATE';
export const VULNERABILITY_ANALYSIS_CREATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const VULNERABILITY_ANALYSIS_READ = 'PORTFOLIO_MANAGEMENT_CREATE';
export const VULNERABILITY_ANALYSIS_UPDATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const VIEW_POLICY_VIOLATION = 'PORTFOLIO_MANAGEMENT_CREATE';
export const VULNERABILITY_MANAGEMENT = 'PORTFOLIO_MANAGEMENT_CREATE';
export const VULNERABILITY_MANAGEMENT_CREATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const VULNERABILITY_MANAGEMENT_READ = 'PORTFOLIO_MANAGEMENT_CREATE';
export const VULNERABILITY_MANAGEMENT_UPDATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const VULNERABILITY_MANAGEMENT_DELETE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const POLICY_VIOLATION_ANALYSIS = 'PORTFOLIO_MANAGEMENT_CREATE';
export const ACCESS_MANAGEMENT = 'PORTFOLIO_MANAGEMENT_CREATE';
export const ACCESS_MANAGEMENT_CREATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const ACCESS_MANAGEMENT_READ = 'PORTFOLIO_MANAGEMENT_CREATE';
export const ACCESS_MANAGEMENT_UPDATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const ACCESS_MANAGEMENT_DELETE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const SYSTEM_CONFIGURATION = 'PORTFOLIO_MANAGEMENT_CREATE';
export const SYSTEM_CONFIGURATION_CREATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const SYSTEM_CONFIGURATION_READ = 'PORTFOLIO_MANAGEMENT_CREATE';
export const SYSTEM_CONFIGURATION_UPDATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const SYSTEM_CONFIGURATION_DELETE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const PROJECT_CREATION_UPLOAD = 'PORTFOLIO_MANAGEMENT_CREATE';
export const POLICY_MANAGEMENT = 'PORTFOLIO_MANAGEMENT_CREATE';
export const POLICY_MANAGEMENT_CREATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const POLICY_MANAGEMENT_READ = 'PORTFOLIO_MANAGEMENT_CREATE';
export const POLICY_MANAGEMENT_UPDATE = 'PORTFOLIO_MANAGEMENT_CREATE';
export const POLICY_MANAGEMENT_DELETE = 'PORTFOLIO_MANAGEMENT_CREATE';

/**
 * Determines if the current logged in user has a specific permission.
 * If the decodedToken is not passed, the function will automatically
 * retrieve and decode it.
 */
export const hasPermission = function hasPermission(permission, decodedToken) {
  const token = decodedToken || decodeToken(getToken());
  const permissions = token?.permissions?.split(',') || [];
  return permissions.includes(permission);
};

/**
 * Returns the decoded token as a JSON object.
 */
export const decodeToken = function decodeToken(token) {
  let base64Url = token.split('.')[1];
  let base64 = base64Url.replace('-', '+').replace('_', '/');
  return JSON.parse(window.atob(base64));
};

/**
 * Retrieves the token from session storage.
 */
export const getToken = function getToken() {
  return sessionStorage.getItem('token');
};
